version: '3'
services:
  nginx:
    image: nginx:latest
    #container_name: website-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/logs:/var/log/nginx
      - ./wordpress:/var/www/html
    links:
      - wordpress:phpfpm
    restart: always
  
  mysql:
    image: mysql:5.7
    #container_name: website-mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    env_file: .env
    restart: always
  
  wordpress:
    image: wordpress:5.0.3-php7.1-fpm-alpine
    #container_name: website-wordpress
    volumes:
      - ./wordpress:/var/www/html
    env_file: .env
    links:
      - mysql
    restart: always
